# pyright: reportUnsupportedDunderAll=false
"""Lightweight Application Service public contract.

The package root is imported by UI modules that only need command dataclasses
or result envelopes. Keep this initializer free of runtime services so opening
the Dataset panel does not import training, torch, sklearn, or visualization.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES: dict[str, str] = {
    # commands
    "ApplyInterpretationCommand": ".commands",
    "ApplyMontageCommand": ".commands",
    "ApplySmartParseCommand": ".commands",
    "AttachLabelsCommand": ".commands",
    "ClearDatasetsCommand": ".commands",
    "ClearTrainingHistoryCommand": ".commands",
    "Command": ".commands",
    "CommandName": ".commands",
    "ConfigureTrainingCommand": ".commands",
    "CreateEpochCommand": ".commands",
    "DatasetGenerationMode": ".commands",
    "EvaluateCommand": ".commands",
    "GenerateDatasetCommand": ".commands",
    "ImportLabelsCommand": ".commands",
    "LabelImportPlan": ".commands",
    "LoadDataCommand": ".commands",
    "MetadataUpdate": ".commands",
    "NewSessionCommand": ".commands",
    "PreprocessCommand": ".commands",
    "PreprocessOperation": ".commands",
    "PreviewLabelImportCommand": ".commands",
    "PreviewInterpretationCommand": ".commands",
    "QueryStateCommand": ".commands",
    "ReloadInterpretationRecipeCommand": ".commands",
    "RemoveFilesCommand": ".commands",
    "ResetPreprocessCommand": ".commands",
    "ResetSessionCommand": ".commands",
    "ReviewInterpretationCommand": ".commands",
    "SaliencyCommand": ".commands",
    "SaveInterpretationRecipeCommand": ".commands",
    "ScanSourceCommand": ".commands",
    "StopTrainingCommand": ".commands",
    "TrainCommand": ".commands",
    "UpdateMetadataCommand": ".commands",
    "ValidateInterpretationCommand": ".commands",
    "VisualizeCommand": ".commands",
    "command_name": ".commands",
    # results
    "ChangedState": ".results",
    "CommandResult": ".results",
    "CommandStatus": ".results",
    "ErrorType": ".results",
    # typed Evaluation render publication
    "EvaluationPlanIdentity": ".evaluation_render",
    "EvaluationRenderData": ".evaluation_render",
    "EvaluationRenderPublication": ".evaluation_render",
    "EvaluationRenderRequest": ".evaluation_render",
    "EvaluationRunIdentity": ".evaluation_render",
    "EvaluationSummaryIdentity": ".evaluation_render",
    # typed Preprocess render publication
    "PreprocessRenderData": ".preprocess_render",
    "PreprocessRenderPublication": ".preprocess_render",
    "PreprocessRenderRequest": ".preprocess_render",
    "PreprocessSignalState": ".preprocess_render",
    "SignalEvent": ".preprocess_render",
    "SignalSeries": ".preprocess_render",
    # typed dataset-splitting publications
    "DatasetSplitChoice": ".dataset_split_preview",
    "DatasetSplitContext": ".dataset_split_preview",
    "DatasetSplitContextPublication": ".dataset_split_preview",
    "DatasetSplitContextRequest": ".dataset_split_preview",
    "DatasetSplitPreviewPublication": ".dataset_split_preview",
    "DatasetSplitPreviewRequest": ".dataset_split_preview",
    "DatasetSplitPreviewRow": ".dataset_split_preview",
    "DatasetSplitRule": ".dataset_split_preview",
    "DatasetSplitSpecification": ".dataset_split_preview",
    # typed visualization render publication
    "SaliencyPlanIdentity": ".saliency_render",
    "SaliencyRenderData": ".saliency_render",
    "SaliencyRenderPublication": ".saliency_render",
    "SaliencyRenderRequest": ".saliency_render",
    "SaliencyRunIdentity": ".saliency_render",
    # capabilities
    "CapabilityPolicy": ".capabilities",
    "CommandCapability": ".capabilities",
    "build_capability_policy": ".capabilities",
    "build_workflow_projection": ".workflow_projection",
    # errors
    "ApplicationError": ".errors",
    "ConfirmationRequiredError": ".errors",
    "PreconditionError": ".errors",
    "map_exception": ".errors",
    # state snapshots
    "ActiveDatasetSnapshot": ".state",
    "ActiveTrainingSnapshot": ".state",
    "ApplicationStateSnapshot": ".state",
    "APPLICATION_VIEW_PUBLICATION_CHANGED_EVENT": ".view_publication",
    "ApplicationViewPublication": ".view_publication",
    "WorkflowProjection": ".workflow_projection",
    "DatasetStateSnapshot": ".state",
    "EpochStateSnapshot": ".state",
    "ErrorSnapshot": ".state",
    "EvaluationStateSnapshot": ".state",
    "InterpretationStateSnapshot": ".state",
    "PreprocessedStateSnapshot": ".state",
    "RawStateSnapshot": ".state",
    "TrainingStateSnapshot": ".state",
    "VisualizationStateSnapshot": ".state",
    # data interpretation value objects
    "AppliedInterpretation": ".data_interpretation",
    "FileMetadataResolution": ".data_interpretation",
    "ImportRecipe": ".data_interpretation",
    "InterpretationCandidate": ".data_interpretation",
    "InterpretationDecision": ".data_interpretation",
    "InterpretationPreview": ".data_interpretation",
    "MetadataFieldResolution": ".data_interpretation",
    "ScanResult": ".data_interpretation",
    "ValidationDecision": ".data_interpretation",
    # heavier runtime/automation exports kept lazy for compatibility
    "ApplicationService": ".service",
    "get_application_service": ".runtime",
    "AutomationCommandSpec": ".automation",
    "AutomationExecution": ".automation",
    "AutomationPayloadError": ".automation",
    "build_command_from_payload": ".automation",
    "command_specs": ".automation",
    "execute_automation_payload": ".automation",
    "mcp_tool_specs": ".automation",
}

__all__ = [
    "APPLICATION_VIEW_PUBLICATION_CHANGED_EVENT",
    "ActiveDatasetSnapshot",
    "ActiveTrainingSnapshot",
    "ApplicationError",
    "ApplicationService",
    "ApplicationStateSnapshot",
    "ApplicationViewPublication",
    "AppliedInterpretation",
    "ApplyInterpretationCommand",
    "ApplyMontageCommand",
    "ApplySmartParseCommand",
    "AttachLabelsCommand",
    "AutomationCommandSpec",
    "AutomationExecution",
    "AutomationPayloadError",
    "CapabilityPolicy",
    "ChangedState",
    "ClearDatasetsCommand",
    "ClearTrainingHistoryCommand",
    "Command",
    "CommandCapability",
    "CommandName",
    "CommandResult",
    "CommandStatus",
    "ConfigureTrainingCommand",
    "ConfirmationRequiredError",
    "CreateEpochCommand",
    "DatasetGenerationMode",
    "DatasetSplitChoice",
    "DatasetSplitContext",
    "DatasetSplitContextPublication",
    "DatasetSplitContextRequest",
    "DatasetSplitPreviewPublication",
    "DatasetSplitPreviewRequest",
    "DatasetSplitPreviewRow",
    "DatasetSplitRule",
    "DatasetSplitSpecification",
    "DatasetStateSnapshot",
    "EpochStateSnapshot",
    "ErrorSnapshot",
    "ErrorType",
    "EvaluateCommand",
    "EvaluationPlanIdentity",
    "EvaluationRenderData",
    "EvaluationRenderPublication",
    "EvaluationRenderRequest",
    "EvaluationRunIdentity",
    "EvaluationStateSnapshot",
    "EvaluationSummaryIdentity",
    "FileMetadataResolution",
    "GenerateDatasetCommand",
    "ImportLabelsCommand",
    "ImportRecipe",
    "InterpretationCandidate",
    "InterpretationDecision",
    "InterpretationPreview",
    "InterpretationStateSnapshot",
    "LabelImportPlan",
    "LoadDataCommand",
    "MetadataFieldResolution",
    "MetadataUpdate",
    "NewSessionCommand",
    "PreconditionError",
    "PreprocessCommand",
    "PreprocessOperation",
    "PreprocessRenderData",
    "PreprocessRenderPublication",
    "PreprocessRenderRequest",
    "PreprocessSignalState",
    "PreprocessedStateSnapshot",
    "PreviewInterpretationCommand",
    "PreviewLabelImportCommand",
    "QueryStateCommand",
    "RawStateSnapshot",
    "ReloadInterpretationRecipeCommand",
    "RemoveFilesCommand",
    "ResetPreprocessCommand",
    "ResetSessionCommand",
    "ReviewInterpretationCommand",
    "SaliencyCommand",
    "SaliencyPlanIdentity",
    "SaliencyRenderData",
    "SaliencyRenderPublication",
    "SaliencyRenderRequest",
    "SaliencyRunIdentity",
    "SaveInterpretationRecipeCommand",
    "ScanResult",
    "ScanSourceCommand",
    "SignalEvent",
    "SignalSeries",
    "StopTrainingCommand",
    "TrainCommand",
    "TrainingStateSnapshot",
    "UpdateMetadataCommand",
    "ValidateInterpretationCommand",
    "ValidationDecision",
    "VisualizationStateSnapshot",
    "VisualizeCommand",
    "WorkflowProjection",
    "build_capability_policy",
    "build_command_from_payload",
    "build_workflow_projection",
    "command_name",
    "command_specs",
    "execute_automation_payload",
    "get_application_service",
    "map_exception",
    "mcp_tool_specs",
]


def __getattr__(name: str) -> Any:
    """Load compatibility exports on demand without broad startup imports."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
