"""Application service API for command-driven backend orchestration."""

from .capabilities import (
    CapabilityPolicy,
    CommandCapability,
    build_capability_policy,
)
from .commands import (
    AttachLabelsCommand,
    Command,
    CommandName,
    ConfigureTrainingCommand,
    CreateEpochCommand,
    EvaluateCommand,
    GenerateDatasetCommand,
    LoadDataCommand,
    NewSessionCommand,
    PreprocessCommand,
    PreprocessOperation,
    ResetSessionCommand,
    SaliencyCommand,
    StopTrainingCommand,
    TrainCommand,
    VisualizeCommand,
    command_name,
)
from .errors import (
    ApplicationError,
    ConfirmationRequiredError,
    PreconditionError,
    map_exception,
)
from .results import ChangedState, CommandResult, CommandStatus, ErrorType
from .service import ApplicationService
from .state import (
    ActiveDatasetSnapshot,
    ActiveTrainingSnapshot,
    ApplicationStateSnapshot,
    DatasetStateSnapshot,
    EpochStateSnapshot,
    ErrorSnapshot,
    EvaluationStateSnapshot,
    PreprocessedStateSnapshot,
    RawStateSnapshot,
    TrainingStateSnapshot,
    VisualizationStateSnapshot,
)

__all__ = [
    "ActiveDatasetSnapshot",
    "ActiveTrainingSnapshot",
    "ApplicationError",
    "ApplicationService",
    "ApplicationStateSnapshot",
    "AttachLabelsCommand",
    "CapabilityPolicy",
    "ChangedState",
    "Command",
    "CommandCapability",
    "CommandName",
    "CommandResult",
    "CommandStatus",
    "ConfigureTrainingCommand",
    "ConfirmationRequiredError",
    "CreateEpochCommand",
    "DatasetStateSnapshot",
    "EpochStateSnapshot",
    "ErrorSnapshot",
    "ErrorType",
    "EvaluateCommand",
    "EvaluationStateSnapshot",
    "GenerateDatasetCommand",
    "LoadDataCommand",
    "NewSessionCommand",
    "PreconditionError",
    "PreprocessCommand",
    "PreprocessOperation",
    "PreprocessedStateSnapshot",
    "RawStateSnapshot",
    "ResetSessionCommand",
    "SaliencyCommand",
    "StopTrainingCommand",
    "TrainCommand",
    "TrainingStateSnapshot",
    "VisualizationStateSnapshot",
    "VisualizeCommand",
    "build_capability_policy",
    "command_name",
    "map_exception",
]
