"""Abstract base class for LLM backends.

Defines the interface that all inference backends (local, API, Gemini)
must implement.
"""

from abc import ABC, abstractmethod


class BaseBackend(ABC):
    """Abstract base class for LLM inference backends.

    Subclasses must implement ``load`` for resource initialization and
    ``generate_stream`` for streaming text generation.
    """

    @abstractmethod
    def load(self):
        """Initializes backend resources (model weights, API client, etc.)."""

    @abstractmethod
    def generate_stream(self, messages: list):
        """Yields text chunks from the LLM.

        Args:
            messages: List of message dicts with ``role`` and ``content``
                keys.

        Yields:
            Text chunks generated by the backend.

        """
