"""Abstract base class for LLM backends.

Defines the interface implemented by the local product inference backend.
"""

from abc import ABC, abstractmethod

from XBrainLab.llm.core.generation import ResolvedGenerationOptions


class BaseBackend(ABC):
    """Abstract base class for LLM inference backends.

    Subclasses must implement ``load`` for resource initialization and
    ``generate_stream`` for streaming text generation.
    """

    @abstractmethod
    def load(self):
        """Initializes backend resources such as local model weights."""

    @abstractmethod
    def generate_stream(
        self,
        messages: list,
        *,
        options: ResolvedGenerationOptions,
    ):
        """Yields text chunks from the LLM.

        Args:
            messages: List of message dicts with ``role`` and ``content``
                keys.
            options: Fully resolved immutable decoding options.

        Yields:
            Text chunks generated by the backend.

        """
